name: Generate ANTLR Sources

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/src/main/antlr/**/*.g4'

jobs:
  generate-antlr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download ANTLR tool
      run: |
        curl -o antlr-4.13.1-complete.jar https://www.antlr.org/download/antlr-4.13.1-complete.jar

    - name: Generate ANTLR sources (Lexer first, then Parser)
      run: |
        mkdir -p app/src/main/java/com/example/codeditor/antlr
        # اول همه فایل‌های Lexer.g4 را تولید کن
        for file in app/src/main/antlr/*JavaLexer.g4; do
          [ -e "$file" ] && java -jar antlr-4.13.1-complete.jar -Dlanguage=Java -visitor -package com.example.codeditor.antlr -o app/src/main/java/com/example/codeditor/antlr "$file"
        done
        # بعد همه فایل‌های Parser.g4 را تولید کن
        for file in app/src/main/antlr/*JavaParser.g4; do
          [ -e "$file" ] && java -jar antlr-4.13.1-complete.jar -Dlanguage=Java -visitor -package com.example.codeditor.antlr -o app/src/main/java/com/example/codeditor/antlr "$file"
        done

    - name: Commit and push generated sources
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add app/src/main/java/com/example/codeditor/antlr
        git commit -m "Generate ANTLR sources [skip ci]" || echo "No changes to commit"
        git push